// Monthly Sales Data
export const monthlySalesData = [
  { month: "January", revenue: 45, target: 50, growth: 5 },
  { month: "February", revenue: 52, target: 55, growth: 15.5 },
  { month: "March", revenue: 48, target: 45, growth: -7.7 },
  { month: "April", revenue: 61, target: 50, growth: 27.1 },
  { month: "May", revenue: 55, target: 60, growth: -9.8 },
  { month: "June", revenue: 67, target: 65, growth: 21.8 },
  { month: "July", revenue: 70, target: 60, growth: 4.5 },
  { month: "August", revenue: 72, target: 75, growth: 2.9 },
  { month: "September", revenue: 81, target: 80, growth: 12.5 },
  { month: "October", revenue: 75, target: 70, growth: -7.4 },
  { month: "November", revenue: 82, target: 80, growth: 9.3 },
  { month: "December", revenue: 91, target: 85, growth: 11.0 },
]

// Product Performance Data (Scatter Plot)
export const productPerformanceData = [
  { name: "Product A", sales: 45, satisfaction: 8.2 },
  { name: "Product B", sales: 72, satisfaction: 9.1 },
  { name: "Product C", sales: 38, satisfaction: 7.8 },
  { name: "Product D", sales: 53, satisfaction: 6.5 },
  { name: "Product E", sales: 29, satisfaction: 8.5 },
  { name: "Product F", sales: 61, satisfaction: 9.3 },
  { name: "Product G", sales: 47, satisfaction: 7.2 },
  { name: "Product H", sales: 83, satisfaction: 8.9 },
  { name: "Product I", sales: 19, satisfaction: 6.8 },
  { name: "Product J", sales: 65, satisfaction: 8.1 },
]

// Market Share Data (Pie Chart)
export const marketShareData = [
  { name: "Electronics", value: 400 },
  { name: "Apparel", value: 300 },
  { name: "Home Goods", value: 200 },
  { name: "Beauty", value: 150 },
  { name: "Food", value: 100 },
]

// Customer Acquisition Data (Area Chart)
export const customerAcquisitionData = [
  { date: "Jan", new: 400, returning: 240 },
  { date: "Feb", new: 300, returning: 278 },
  { date: "Mar", new: 200, returning: 290 },
  { date: "Apr", new: 278, returning: 320 },
  { date: "May", new: 189, returning: 384 },
  { date: "Jun", new: 239, returning: 390 },
  { date: "Jul", new: 349, returning: 430 },
  { date: "Aug", new: 431, returning: 456 },
  { date: "Sep", new: 382, returning: 521 },
  { date: "Oct", new: 310, returning: 490 },
  { date: "Nov", new: 401, returning: 530 },
  { date: "Dec", new: 452, returning: 590 },
]

// Revenue by Channel Data
export const revenueByChannelData = [
  { name: "Direct", value: 400 },
  { name: "Social Media", value: 300 },
  { name: "Email", value: 250 },
  { name: "Affiliates", value: 200 },
  { name: "Search", value: 350 },
  { name: "Referral", value: 150 },
]

// Table Data
export const tableData = [
  {
    id: 1,
    name: "John Smith",
    email: "john.smith@example.com",
    category: "Electronics",
    amount: 299.99,
    status: "active",
    date: "2023-12-15",
  },
  {
    id: 2,
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    category: "Apparel",
    amount: 89.95,
    status: "pending",
    date: "2023-12-12",
  },
  {
    id: 3,
    name: "Michael Brown",
    email: "m.brown@example.com",
    category: "Home Goods",
    amount: 149.5,
    status: "active",
    date: "2023-12-10",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    category: "Beauty",
    amount: 65.75,
    status: "inactive",
    date: "2023-12-05",
  },
  {
    id: 5,
    name: "David Wilson",
    email: "d.wilson@example.com",
    category: "Electronics",
    amount: 499.99,
    status: "active",
    date: "2023-12-01",
  },
  {
    id: 6,
    name: "Jessica Martinez",
    email: "j.martinez@example.com",
    category: "Food",
    amount: 32.5,
    status: "pending",
    date: "2023-11-28",
  },
  {
    id: 7,
    name: "Robert Taylor",
    email: "robert.t@example.com",
    category: "Apparel",
    amount: 129.95,
    status: "active",
    date: "2023-11-25",
  },
  {
    id: 8,
    name: "Jennifer Anderson",
    email: "j.anderson@example.com",
    category: "Home Goods",
    amount: 199.99,
    status: "active",
    date: "2023-11-20",
  },
  {
    id: 9,
    name: "Christopher Thomas",
    email: "c.thomas@example.com",
    category: "Electronics",
    amount: 349.99,
    status: "inactive",
    date: "2023-11-15",
  },
  {
    id: 10,
    name: "Lisa Jackson",
    email: "lisa.j@example.com",
    category: "Beauty",
    amount: 45.25,
    status: "active",
    date: "2023-11-10",
  },
  {
    id: 11,
    name: "Daniel White",
    email: "d.white@example.com",
    category: "Food",
    amount: 28.75,
    status: "pending",
    date: "2023-11-05",
  },
  {
    id: 12,
    name: "Michelle Harris",
    email: "m.harris@example.com",
    category: "Apparel",
    amount: 159.95,
    status: "active",
    date: "2023-11-01",
  },
  {
    id: 13,
    name: "James Martin",
    email: "james.m@example.com",
    category: "Electronics",
    amount: 599.99,
    status: "active",
    date: "2023-10-28",
  },
  {
    id: 14,
    name: "Patricia Thompson",
    email: "p.thompson@example.com",
    category: "Home Goods",
    amount: 249.5,
    status: "inactive",
    date: "2023-10-25",
  },
  {
    id: 15,
    name: "Richard Garcia",
    email: "r.garcia@example.com",
    category: "Beauty",
    amount: 55.99,
    status: "active",
    date: "2023-10-20",
  },
  {
    id: 16,
    name: "Linda Rodriguez",
    email: "l.rodriguez@example.com",
    category: "Food",
    amount: 42.25,
    status: "pending",
    date: "2023-10-15",
  },
  {
    id: 17,
    name: "William Martinez",
    email: "w.martinez@example.com",
    category: "Apparel",
    amount: 119.95,
    status: "active",
    date: "2023-10-10",
  },
  {
    id: 18,
    name: "Elizabeth Clark",
    email: "e.clark@example.com",
    category: "Electronics",
    amount: 449.99,
    status: "active",
    date: "2023-10-05",
  },
  {
    id: 19,
    name: "Thomas Lewis",
    email: "t.lewis@example.com",
    category: "Home Goods",
    amount: 179.5,
    status: "inactive",
    date: "2023-10-01",
  },
  {
    id: 20,
    name: "Barbara Walker",
    email: "b.walker@example.com",
    category: "Beauty",
    amount: 39.99,
    status: "active",
    date: "2023-09-28",
  },
  {
    id: 21,
    name: "Joseph Hall",
    email: "j.hall@example.com",
    category: "Food",
    amount: 35.5,
    status: "pending",
    date: "2023-09-25",
  },
  {
    id: 22,
    name: "Susan Allen",
    email: "s.allen@example.com",
    category: "Apparel",
    amount: 139.95,
    status: "active",
    date: "2023-09-20",
  },
  {
    id: 23,
    name: "Charles Young",
    email: "c.young@example.com",
    category: "Electronics",
    amount: 529.99,
    status: "active",
    date: "2023-09-15",
  },
  {
    id: 24,
    name: "Margaret Hernandez",
    email: "m.hernandez@example.com",
    category: "Home Goods",
    amount: 219.5,
    status: "inactive",
    date: "2023-09-10",
  },
  {
    id: 25,
    name: "Kevin King",
    email: "k.king@example.com",
    category: "Beauty",
    amount: 49.99,
    status: "active",
    date: "2023-09-05",
  },
  {
    id: 26,
    name: "Dorothy Wright",
    email: "d.wright@example.com",
    category: "Food",
    amount: 31.75,
    status: "pending",
    date: "2023-09-01",
  },
  {
    id: 27,
    name: "Brian Lopez",
    email: "b.lopez@example.com",
    category: "Apparel",
    amount: 149.95,
    status: "active",
    date: "2023-08-28",
  },
  {
    id: 28,
    name: "Karen Hill",
    email: "k.hill@example.com",
    category: "Electronics",
    amount: 399.99,
    status: "active",
    date: "2023-08-25",
  },
  {
    id: 29,
    name: "Ronald Scott",
    email: "r.scott@example.com",
    category: "Home Goods",
    amount: 189.5,
    status: "inactive",
    date: "2023-08-20",
  },
  {
    id: 30,
    name: "Helen Green",
    email: "h.green@example.com",
    category: "Beauty",
    amount: 59.99,
    status: "active",
    date: "2023-08-15",
  },
]
